server:
  port: 8082
spring:
#  datasource:
#    username: root
#    password: yy123456
#    url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master,slave0
      # 数据源 主库
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: yy123456
      # 数据源 从库
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
        username: root
        password: abe47ec48cc99166
    # 读写分离
    masterslave:
      load-balance-algorithm-type: round_robin
      name: ms
      master-data-source-name: master
      slave-data-source-names: slave0
    #打印sql
#    props.sql.show: true
  neo4j:
    security:
      hostname-verification-enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: false
    url: jdbc:mysql://127.0.0.1:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    user: root
    password: yy123456

  aop:
    auto: true
    proxy-target-class: true
mybatis:
   mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.example.vhr: debug
    org.springframework.boot.autoconfigure: error


#  type-aliases-package: vhr_model/src/main/java/org.example.vhr
#JWT存储的请求头

jwt:
  tokenHeader: Authorization
  #JWT加解密使用的密钥
  secret: mall-admin-secret
  #JWT的超期限时间(60*60*24*7)
  expiration: 604800
  #JWT负载中拿到开头
  tokenHead: 'Bearer '

