server:
  port: 8082
spring:
  datasource:
    username: root
    password: yy123456
    url: jdbc:mysql://139.196.198.33:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  neo4j:
    security:
      hostname-verification-enabled: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: false
  aop:
    auto: true
    proxy-target-class: true
mybatis:
   mapper-locations: classpath:mapper/*.xml
logging:
  level:
    org.example.vhr: debug
    org.springframework.boot.autoconfigure: error


#  type-aliases-package: vhr_model/src/main/java/org.example.vhr
#JWT存储的请求头

jwt:
  tokenHeader: Authorization
  #JWT加解密使用的密钥
  secret: mall-admin-secret
  #JWT的超期限时间(60*60*24*7)
  expiration: 604800
  #JWT负载中拿到开头
  tokenHead: 'Bearer '

